const weatherIcons = {
  clear: "./CSS/icons/sun.png",
  mainlyClear: "./CSS/icons/mainly-clear.png",
  overcast: "./CSS/icons/overcast.png",
  fog: "./CSS/icons/fog.png",
  lightRain: "./CSS/icons/light-rain.png",
  rain: "./CSS/icons/rain.png",
  sleet: "./CSS/icons/sleet.png",
  lightSnow: "./CSS/icons/light-snow.png",
  snow: "./CSS/icons/snow.png",
  thunderstorm: "./CSS/icons/thunderstorm.png",
};

export const weatherCode = {
  0: weatherIcons.clear,
  1: weatherIcons.mainlyClear,
  2: weatherIcons.mainlyClear,
  3: weatherIcons.overcast,
  45: weatherIcons.fog,
  48: weatherIcons.fog,
  51: weatherIcons.lightRain,
  53: weatherIcons.lightRain,
  55: weatherIcons.rain,
  56: weatherIcons.sleet,
  57: weatherIcons.sleet,
  61: weatherIcons.lightRain,
  63: weatherIcons.rain,
  65: weatherIcons.rain,
  66: weatherIcons.sleet,
  67: weatherIcons.sleet,
  71: weatherIcons.lightSnow,
  73: weatherIcons.snow,
  75: weatherIcons.snow,
  77: weatherIcons.lightSnow,
  80: weatherIcons.lightRain,
  81: weatherIcons.rain,
  82: weatherIcons.rain,
  85: weatherIcons.lightSnow,
  86: weatherIcons.snow,
  95: weatherIcons.thunderstorm,
  96: weatherIcons.thunderstorm,
  99: weatherIcons.thunderstorm,
};

export const typeArrays = {
  foodAmenity: ["restaurant", "fast_food", "cafe"],
  outdoorAmenity: [
    "park",
    "nature_reserve",
    "wood",
    "beach",
    "cliff",
    "memorial",
    "monument",
    "ruins",
    "viewpoint",
  ],
  indoorAmenities: ["artwork", "escape_game", "museum", "amusement_arcade"],
  kidsAmenities: [
    "amusement_arcade",
    "playground",
    "water_park",
    "museum",
    "park",
  ],
  entertainmentAmenities: [
    "amusement_arcade",
    "escape_game",
    "water_park",
    "attraction",
  ],
};
